name: pr-main-test
run-name: Validating a Pull Request to main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/*

env:
  TFSTATE_BUCKET: lambda-tfstate-output-retriever-tfstate
  AWS_REGION: eu-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/environment-setup.yml
      - run: make apply
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/environment-setup.yml
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: make test
  teardown:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/environment-setup.yml
      - run: make destroy
